steps:
  - name: gcr.io/cloud-builders/gsutil
    allowFailure: true
    args:
      [
        "-m",
        "rsync",
        "-r",
        "-c",
        "-d",
        "gs://sato-build-cache/website/.yarn/cache",
        "./ssg/.yarn/cache",
      ]

  - name: "gcr.io/cloud-builders/yarn"
    args:
      - install
    dir: "./ssg"

  - name: "gcr.io/cloud-builders/yarn"
    args:
      - build
    dir: "./ssg"
    secretEnv: ["CMS_URL"]
    env:
      - "PATH_PREFIX=sato-website"

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./ssg/_site", "gs://sato-website"]

  - name: gcr.io/cloud-builders/gsutil
    args:
      [
        "-m",
        "rsync",
        "-r",
        "-c",
        "-d",
        "./ssg/.yarn/cache",
        "gs://sato-build-cache/website/.yarn/cache",
      ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/CMS_URL/versions/latest
      env: "CMS_URL"
