steps:
  - name: node
    args: [install]
    dir: "./ssg"

  - name: node
    args: [build]
    dir: "./ssg"
    secretEnv: ["CMS_URL"]
    env:
      - "PATH_PREFIX=sato-website"

  - name: gcr.io/cloud-builders/gsutil
    args:
      [
        "-m",
        "rsync",
        "-r",
        "-c",
        "-J",
        "-d",
        "./ssg/_site",
        "gs://sato-website",
      ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/CMS_URL/versions/latest
      env: "CMS_URL"
