services:
  frontend:
    image: node:alpine
    volumes:
      - ./frontend:/usr/app
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
    working_dir: /usr/app

  strapi:
    image: naskio/strapi:latest-alpine
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    ports:
      - 1337:1337
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data